version: "2.1"
networks:
  netmonk:

volumes:
  influxdb_vol:
  mongodb_vol:
  mongodb_config:

services:
  kafka:
    image: spotify/kafka
    ports: 
      - "2181:2181"
      - "9092:9092"
    networks: 
      netmonk:
        aliases:
          - kafka
          - message-broker.jeager.ketitik.com
    environment:
      - KAFKA_OPTS=-Djava.security.auth.login.config=/opt/kafka_plain_jaas.conf
    volumes:
      - "${PWD}/conf_kafka/kafka_plain_jaas.conf:/opt/kafka_plain_jaas.conf"
      - "${PWD}/conf_kafka/server.properties:/opt/kafka_2.11-0.10.1.0/config/server.properties"
      - "${PWD}/conf_kafka/zookeeper.properties:/opt/kafka_2.11-0.10.1.0/config/zookeeper.properties"
      - "${PWD}/bash_kafka:/home/ubuntu"
    command: bash -c "/home/ubuntu/start-all.sh"

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      netmonk:
        aliases:
          - influxdb
    volumes:
      - "influxdb_vol:/var/lib/influxdb"
    environment:
     - INFLUXDB_DB=${INFLUX_DB}
     - INFLUXDB_ADMIN_ENABLED=true
     - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUX_HTTP_AUTH}
     - INFLUXDB_ADMIN_USER=${INFLUX_USERNAME} 
     - INFLUXDB_ADMIN_PASSWORD=${INFLUX_PASSWORD}
    privileged: true

  telegraf:
    image: telegraf
    networks:
      netmonk:
        aliases:
          - telegraf
    volumes:
      - ${PWD}/conf_telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    privileged: true
    depends_on:
      - kafka
      - influxdb
    restart: always

  mongodb:
    image: mongo
    restart: always
    networks:
      netmonk:
        aliases:
          - mongonodemonk
    ports:
      - "27017:27017"
    volumes:
      - "${PWD}/conf_mongodb:/docker-entrypoint-initdb.d"
      - "mongodb_vol:/data/db"
      - "mongodb_config:/data/configdb"
