version: "2.1"
networks:
  netmonk:

services:

  kafka:
    image: spotify/kafka
    ports: 
      - "2181:2181"
      - "9092:9092"
    networks: 
      netmonk:
        aliases:
          - kafka
    environment:
      - ADVERTISED_HOST=192.168.43.235
      - ADVERTISED_PORT=9092

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      netmonk:
        aliases:
          - influxdb
    environment:
     - INFLUXDB_DB=${INFLUX_DB}
     - INFLUXDB_ADMIN_ENABLED=true
     - INFLUXDB_HTTP_AUTH_ENABLED=${INFLUX_HTTP_AUTH}
     - INFLUXDB_ADMIN_USER=${INFLUX_USERNAME} 
     - INFLUXDB_ADMIN_PASSWORD=${INFLUX_PASSWORD}
    privileged: true

  telegraf:
    image: telegraf
    networks:
      netmonk:
        aliases:
          - telegraf
    volumes:
      - ${PWD}/conf_telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    privileged: true
    depends_on:
      - kafka
      - influxdb
    restart: always