version: "2.1"
networks:
  netmonk:

services:
  telegraf:
    image: telegraf
    networks:
      netmonk:
        aliases:
          - telegraf
    volumes:
      - ${PWD}/conf_telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    privileged: true
    restart: always